--- # Ansible Playbook f端r (statische) Konfiguration eines Offloader auf Basis eines Raspberry PI 4B
- name:         raspi_offloader.yml 
  hosts:        raspberry-wireguard
  become:       yes
  become_user:  root
  
  tags:
    - basicsetup
  roles:
    - basic         # Basiskonfiguration des Hosts (Host-/Username anpassen und System Updaten)
    - batman        # Installation und Konfiguration der BATMAN Kernel-Module
    - wireguard     # Installation und Konfiguration des wireguard Tunnels
    - vxlan         # Konfiguration von VXLAN f端r wireguard-Tunnel-Verbindung in Richtung Gateway
    - ext-respondd  # Installation und Konfiguration des ext-respondd (Statistiken f端r https://map.ffmuc.net)
    - hostapd       # Installation und Konfiguration des hostap Treibers f端r den WiFi-Support
    - client-mesh   # Grundkonfiguration von Client und/oder Meshing (V)LANs
    - oled          # Konfiguration eines OLEDisplays sofern eines am Respberry 4B verbaut ist
    - final         # Reboot nach Abschluss der Konfiguration unseres Offloaders 

- name: IP-Tables
  hosts: raspberry-wireguard
  tags:
    - iptables
  roles:
    - iptables

- name: Fail2Ban
  hosts: raspberry-wireguard
  tags:
    - fail2ban
  roles:
    - fail2ban

... # YML Ende
