---
  - name: "Für OLED-Konfiguration i2c-bcm2708 in /etc/modules eintragen"
    # https://docs.ansible.com/ansible/latest/modules/shell_module.html
    shell: echo i2c-bcm2708 >> /etc/modules
    when: ( raspberry_oled == "ja" )
