---
  - name: "Laden des Kernelmodul i2c_arm beim Booten veranlassen"
    # https://docs.ansible.com/ansible/latest/modules/template_module.html
    template: 
      src: templates/config.j2
      dest: /boot/config.txt
    when: ( raspberry_oled == "ja" )
