---
  - name: "Installation der für das OLED benötigten Pakete"
    # https://docs.ansible.com/ansible/latest/modules/apt_module.html
    apt:
      update_cache: yes
      pkg:
        - python3-dev
        - python3-smbus
        - i2c-tools
        - python3-pil
        - python3-pip
        - python3-setuptools
        - python3-rpi.gpio
        - git
        - fonts-freefont-ttf
      state: present
    when: ( raspberry_oled == "ja" ) 
