---
  - name: "*VXLAN* : systemd-unitfile anlegen"
    # https://docs.ansible.com/ansible/latest/modules/template_module.html
    template:
      src: templates/systemd-service-file.j2
      dest: /etc/systemd/system/vxlan.service

  - name: "*VXLAN* : Neues Unitfile dem systemd bekannt geben"
    # https://docs.ansible.com/ansible/latest/modules/systemd_module.html
    systemd:
      daemon_reload: yes

  - name: "*VXLAN* : Service vxlan via systemd starten"
    # https://docs.ansible.com/ansible/latest/modules/systemd_module.html
    systemd:
      name: vxlan.service
      daemon_reload: yes
      state: started
      enabled: yes
