---
  - name: "                               : Erstellen der fastd Konfigurationsdatei"
    # https://docs.ansible.com/ansible/latest/modules/template_module.html
    template: 
      src: templates/fastd.j2
      dest: /etc/fastd/{{ ffmuc_segment }}/fastd.conf
