---
- name: Install Fail2Ban
  become: yes
  apt:
    cache_valid_time: 3600
    pkg:
      - fail2ban
    state: present

- name: fail2ban configuration file update
  become: yes
  template: src=jail.local.j2
    dest=/etc/fail2ban/jail.local
    backup=yes
    owner=0 group=0 mode=0644

- name: Restart fail2ban
  become: true
  systemd:
    name: fail2ban
    state: restarted
    daemon_reload: yes
    enabled: yes
