--- # Installation und Konfiguration des hostap Treibers für den WiFi-Support
- include: install.yml                  # Paket hostapd für WLAN installieren
- include: configure.yml                # hostapd konfigurieren
- include: genconfig.yml                # hostapd Konfigurationsdatei anlegen
- include: wlanbridging.yml             # wlan0 in Bridge packen
- include: servicestartup.yml           # Service hostapd beim Booten und jetzt starten und das Laden der Unit Datei vom Service hostapd ermöglichen
