--- #YAML start syntax (optional)
ffmuc:
  children:
    ffmuc_deb:
      vars:
        ansible_ssh_user: pi
        ansible_ssh_private_key_file: "~/.ssh/id_ed25519_ffmuc_offloaderpi"
      hosts:
        raspberry-wireguard:
          wireguard_ports:
            muc_cty:            40002
            muc_nord:           40003
            muc_ost:            40004
            muc_sued:           40005
            muc_west:           40006
            uml_nord:           40007
            uml_ost:            40008
            uml_sued:           40009
            uml_west:           40010
            gauting:            40012
            freising:           40013
            welt:               40011
          vxlan_ids:
            muc_cty:            10758607
            muc_nord:           15521492
            muc_ost:            2948862
            muc_sued:           8599288
            muc_west:           7318933
            uml_nord:           5705961
            uml_ost:            4892713
            uml_sued:           16544703
            uml_west:           16677749
            gauting:            16175732
            freising:           12937858
            welt:               16306234
          gw_linklocal:
            gw04:               "fe80::27c:16ff:fec0:6c74"
            gw05:               "fe80::281:8eff:fef0:73aa"
            gw06:               "fe80::2a2:e4ff:fef9:2269"
            gw07:               "fe80::23b:d2ff:fe95:967f"
          gw_publickey:
            gw04:               "TszFS3oFRdhsJP3K0VOlklGMGYZy+oFCtlaghXJqW2g="
            gw05:               "igyqOmWiz4EZxPG8ZzU537MnHhaqlwfa7HarB3KmnEg="
            gw06:               "pkRaUOoLuuHnUt9BEGeKrhF3OMYBPecc0iYkika6uhE="
            gw07:               "PcKkakZcTEx3LKh+G06Opb8/esg08aWK33A5/Ff1YXE="
          gw_vxlan_ids:
            muc_cty:            3836090
            muc_nord:           1920014
            muc_ost:            12097488
            muc_sued:           12815947
            muc_west:           29149
            uml_nord:           403289
            uml_ost:            12645856
            uml_sued:           12090508
            uml_west:           935867
            gauting:            4681119
            freising:           4669918
            welt:               4831583
          batman_adv_version:   "2020.4"
          ffmuc_segment:        "welt"
          ffmuc_gateway:        "gw06"
          raspberry_hostname:   "rpb4-wg-ansible-v5-firstrun"
          node_contact_address: "hier entlang => https://bit.ly/2VxGoXp"
          raspberry_latitude:   "48.198724490"
          raspberry_longitude:  "11.798034310"
          raspberry_wifi:       "ja"
          raspberry_clientvlan: "4"
          raspberry_meshvlan:   "2"
          raspberry_oled:       "nein"
          dtparam:              "i2c_arm=on"
... #YAML ende syntax (optional)
