---
  - name: "*BATMAN Installation* : Download des aktuellen BATMAN Archives"
    # https://docs.ansible.com/ansible/latest/modules/get_url_module.html
    get_url: 
      url: https://downloads.open-mesh.org/batman/releases/batman-adv-{{ batman_adv_version }}/batman-adv-{{ batman_adv_version }}.tar.gz
      dest: /usr/src/batman-adv-{{ batman_adv_version }}.tar.gz
      mode: '0644'

  - name: "*BATMAN Installation* : Entpacken des BATMAN-Archives"
    # https://docs.ansible.com/ansible/latest/modules/unarchive_module.html
    unarchive:
      src: /usr/src/batman-adv-{{ batman_adv_version }}.tar.gz
      dest: /usr/src
      remote_src: yes
