---
  - name: "*BATMAN load-modules* : Laden der BATMAN Dynamic Kernel Module beim Booten sicherstellen"
    # https://docs.ansible.com/ansible/latest/modules/template_module.html
    template: 
      src: templates/batman-adv.module.j2
      dest: /etc/modules-load.d/batman-adv.module.conf

  - name: "*BATMAN load-modules* : dummy Modul laden"
    # https://docs.ansible.com/ansible/latest/modules/modprobe_module.html
    modprobe: 
      name: dummy
      state: present

  - name: "*BATMAN load-modules* : BATMAN-ADV Modul laden"
    # https://docs.ansible.com/ansible/latest/modules/modprobe_module.html
    modprobe: 
      name: batman_adv
      state: present
