---
  - name: "*utils-installation* : Installation der bridge-utils"
    # https://docs.ansible.com/ansible/latest/modules/apt_module.html
    apt: 
      #update_cache: yes
      pkg:
       - bridge-utils
       - dnsutils
       - vim
      state: present

  - name: "*utils-installation* : Installation des batctl-packages"
    # https://docs.ansible.com/ansible/latest/modules/apt_module.html
    apt:
      #update_cache: yes
      pkg:
      - batctl
      default_release: buster-backports
      state: present
